### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by boushka9** [boushka9/last-minute-plans#4]
When I visit the application, 
I am presented with an attractive user interface with a clear color palette with accessible contrast 
When I view the app on my phone, 
Then the recipe and movie images fit my screen,
When I resize my window, 
Then the page resizes to better fit the screen

**Comment by boushka9** [comment]
When I am taken to a new page after submitting my search criteria, requesting a random suggestion, or clicking on my saved plans,
Then I see the applications design is uniform across the different pages and match the homepage

**Comment by Tiffas44** [comment]
I will be utilizing youtube and other online resources to help me with the CSS design/Materialize.
